// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drjxjrvtmonymuaaobon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRyanhqcnZ0bW9ueW11YWFvYm9uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMDY2MTcsImV4cCI6MjA2MjY4MjYxN30.eJD01XXeWRUhi3HFdbGQ7lzWLvObXk8KbNpbFrLf-Fc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);